@Library('blackduck-logs-publisher') _

pipeline {
    agent { label 'mac-sh' }

    stages {
        stage("Build") {
            steps {
                script {
                    echo "JOB_NAME: ${env.JOB_NAME}"

                    dir('nodejs-npm') {
                        sh 'node --version'
                        sh 'npm --version'
                        sh 'npm install'
                    }
                }
            }
        }

        stage("blackduck-security-scan") {
            steps {
                script {
                    dir('nodejs-npm') {
                        def projectName = env.JOB_NAME.split('/')[0]
                        echo "DETECT_PROJECT_NAME will be set to: ${projectName}"

                        withEnv(["DETECT_PROJECT_NAME=${projectName}"]) {
                            echo "Workspace is ${WORKSPACE}"
                            security_scan blackducksca_fixpr_enabled: true, blackducksca_fixpr_filter_severities: 'CRITICAL,HIGH',
                                         blackducksca_fixpr_maxCount: 2, blackducksca_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM', 
                                         detect_args: 'detect.source.path=${WORKSPACE}/nodejs-npm', blackducksca_waitForScan: true, product: 'blackducksca' 
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            pushJenkinsLogsToGitHub([
                githubOrg: 'blackducksca-jenkins-samples',
                repoName: 'automatic-fixpr',
                retentionCount: 5
            ])
        }
    }
}
